// 类型定义
interface HIDKey {
  key: number
  word: string
  dec: string
  hex: string
  kind: number
  value: number
  aliases?: string[] // 可选别名数组
}

export const hidKeyCode = [
  // 字母键（合并大小写，无组合形式）
  {
    key: 0,
    word: 'a',
    dec: '4',
    hex: '04',
    kind: 1,
    value: 4,
    aliases: ['A'],
  },
  {
    key: 2,
    word: 'b',
    dec: '5',
    hex: '05',
    kind: 1,
    value: 5,
    aliases: ['B'],
  },
  {
    key: 4,
    word: 'c',
    dec: '6',
    hex: '06',
    kind: 1,
    value: 6,
    aliases: ['C'],
  },
  {
    key: 6,
    word: 'd',
    dec: '7',
    hex: '07',
    kind: 1,
    value: 7,
    aliases: ['D'],
  },
  {
    key: 8,
    word: 'e',
    dec: '8',
    hex: '08',
    kind: 1,
    value: 8,
    aliases: ['E'],
  },
  {
    key: 10,
    word: 'f',
    dec: '9',
    hex: '09',
    kind: 1,
    value: 9,
    aliases: ['F'],
  },
  {
    key: 12,
    word: 'g',
    dec: '10',
    hex: '0A',
    kind: 1,
    value: 10,
    aliases: ['G'],
  },
  {
    key: 14,
    word: 'h',
    dec: '11',
    hex: '0B',
    kind: 1,
    value: 11,
    aliases: ['H'],
  },
  {
    key: 16,
    word: 'i',
    dec: '12',
    hex: '0C',
    kind: 1,
    value: 12,
    aliases: ['I'],
  },
  {
    key: 18,
    word: 'j',
    dec: '13',
    hex: '0D',
    kind: 1,
    value: 13,
    aliases: ['J'],
  },
  {
    key: 20,
    word: 'k',
    dec: '14',
    hex: '0E',
    kind: 1,
    value: 14,
    aliases: ['K'],
  },
  {
    key: 22,
    word: 'l',
    dec: '15',
    hex: '0F',
    kind: 1,
    value: 15,
    aliases: ['L'],
  },
  {
    key: 24,
    word: 'm',
    dec: '16',
    hex: '10',
    kind: 1,
    value: 16,
    aliases: ['M'],
  },
  {
    key: 26,
    word: 'n',
    dec: '17',
    hex: '11',
    kind: 1,
    value: 17,
    aliases: ['N'],
  },
  {
    key: 28,
    word: 'o',
    dec: '18',
    hex: '12',
    kind: 1,
    value: 18,
    aliases: ['O'],
  },
  {
    key: 30,
    word: 'p',
    dec: '19',
    hex: '13',
    kind: 1,
    value: 19,
    aliases: ['P'],
  },
  {
    key: 32,
    word: 'q',
    dec: '20',
    hex: '14',
    kind: 1,
    value: 20,
    aliases: ['Q'],
  },
  {
    key: 34,
    word: 'r',
    dec: '21',
    hex: '15',
    kind: 1,
    value: 21,
    aliases: ['R'],
  },
  {
    key: 36,
    word: 's',
    dec: '22',
    hex: '16',
    kind: 1,
    value: 22,
    aliases: ['S'],
  },
  {
    key: 38,
    word: 't',
    dec: '23',
    hex: '17',
    kind: 1,
    value: 23,
    aliases: ['T'],
  },
  {
    key: 40,
    word: 'u',
    dec: '24',
    hex: '18',
    kind: 1,
    value: 24,
    aliases: ['U'],
  },
  {
    key: 42,
    word: 'v',
    dec: '25',
    hex: '19',
    kind: 1,
    value: 25,
    aliases: ['V'],
  },
  {
    key: 44,
    word: 'w',
    dec: '26',
    hex: '1A',
    kind: 1,
    value: 26,
    aliases: ['W'],
  },
  {
    key: 46,
    word: 'x',
    dec: '27',
    hex: '1B',
    kind: 1,
    value: 27,
    aliases: ['X'],
  },
  {
    key: 48,
    word: 'y',
    dec: '28',
    hex: '1C',
    kind: 1,
    value: 28,
    aliases: ['Y'],
  },
  {
    key: 50,
    word: 'z',
    dec: '29',
    hex: '1D',
    kind: 1,
    value: 29,
    aliases: ['Z'],
  },

  // 数字和符号键（添加组合形式别名）
  {
    key: 52,
    word: '1',
    dec: '30',
    hex: '1E',
    kind: 1,
    value: 30,
    aliases: ['!', '1!'],
  },
  {
    key: 54,
    word: '2',
    dec: '31',
    hex: '1F',
    kind: 1,
    value: 31,
    aliases: ['@', '2@'],
  },
  {
    key: 56,
    word: '3',
    dec: '32',
    hex: '20',
    kind: 1,
    value: 32,
    aliases: ['#', '3#'],
  },
  {
    key: 58,
    word: '4',
    dec: '33',
    hex: '21',
    kind: 1,
    value: 33,
    aliases: ['$', '4$'],
  },
  {
    key: 60,
    word: '5',
    dec: '34',
    hex: '22',
    kind: 1,
    value: 34,
    aliases: ['%', '5%'],
  },
  {
    key: 62,
    word: '6',
    dec: '35',
    hex: '23',
    kind: 1,
    value: 35,
    aliases: ['^', '6^'],
  },
  {
    key: 64,
    word: '7',
    dec: '36',
    hex: '24',
    kind: 1,
    value: 36,
    aliases: ['&', '7&'],
  },
  {
    key: 66,
    word: '8',
    dec: '37',
    hex: '25',
    kind: 1,
    value: 37,
    aliases: ['*', '8*'],
  },
  {
    key: 68,
    word: '9',
    dec: '38',
    hex: '26',
    kind: 1,
    value: 38,
    aliases: ['(', '9('],
  },
  {
    key: 70,
    word: '0',
    dec: '39',
    hex: '27',
    kind: 1,
    value: 39,
    aliases: [')', '0)'],
  },
  {
    key: 77,
    word: '-',
    dec: '45',
    hex: '2D',
    kind: 1,
    value: 45,
    aliases: ['_', '-_'],
  },
  {
    key: 79,
    word: '=',
    dec: '46',
    hex: '2E',
    kind: 1,
    value: 46,
    aliases: ['+', '=+'],
  },
  {
    key: 81,
    word: '[',
    dec: '47',
    hex: '2F',
    kind: 1,
    value: 47,
    aliases: ['{', '[{'],
  },
  {
    key: 83,
    word: ']',
    dec: '48',
    hex: '30',
    kind: 1,
    value: 48,
    aliases: ['}', '}]'],
  },
  {
    key: 85,
    word: '\\',
    dec: '49',
    hex: '31',
    kind: 1,
    value: 49,
    aliases: ['|', '\\|'],
  },
  {
    key: 87,
    word: '`',
    dec: '50',
    hex: '32',
    kind: 1,
    value: 50,
    aliases: ['~', '`~'],
  },
  {
    key: 89,
    word: ';',
    dec: '51',
    hex: '33',
    kind: 1,
    value: 51,
    aliases: [':', ';:'],
  },
  {
    key: 91,
    word: "'",
    dec: '52',
    hex: '34',
    kind: 1,
    value: 52,
    aliases: ['"', '\'"'],
  },
  {
    key: 95,
    word: ',',
    dec: '54',
    hex: '36',
    kind: 1,
    value: 54,
    aliases: ['<', ',<'],
  },
  {
    key: 97,
    word: '.',
    dec: '55',
    hex: '37',
    kind: 1,
    value: 55,
    aliases: ['>', '.>'],
  },
  {
    key: 99,
    word: '/',
    dec: '56',
    hex: '38',
    kind: 1,
    value: 56,
    aliases: ['?', '/?'],
  },

  // 特殊功能键（无重复，保持原样）
  { key: 72, word: 'Enter', dec: '40', hex: '28', kind: 1, value: 40 },
  { key: 73, word: 'Escape', dec: '41', hex: '29', kind: 1, value: 41 },
  { key: 74, word: 'Backspace', dec: '42', hex: '2A', kind: 1, value: 42 },
  { key: 75, word: 'Tab', dec: '43', hex: '2B', kind: 1, value: 43 },
  { key: 76, word: ' ', dec: '44', hex: '2C', kind: 1, value: 44 },
  { key: 101, word: 'CapsLock', dec: '57', hex: '39', kind: 1, value: 57 },
  { key: 102, word: 'F1', dec: '58', hex: '3A', kind: 1, value: 58 },
  { key: 103, word: 'F2', dec: '59', hex: '3B', kind: 1, value: 59 },
  { key: 104, word: 'F3', dec: '60', hex: '3C', kind: 1, value: 60 },
  { key: 105, word: 'F4', dec: '61', hex: '3D', kind: 1, value: 61 },
  { key: 106, word: 'F5', dec: '62', hex: '3E', kind: 1, value: 62 },
  { key: 107, word: 'F6', dec: '63', hex: '3F', kind: 1, value: 63 },
  { key: 108, word: 'F7', dec: '64', hex: '40', kind: 1, value: 64 },
  { key: 109, word: 'F8', dec: '65', hex: '41', kind: 1, value: 65 },
  { key: 110, word: 'F9', dec: '66', hex: '42', kind: 1, value: 66 },
  { key: 111, word: 'F10', dec: '67', hex: '43', kind: 1, value: 67 },
  { key: 112, word: 'F11', dec: '68', hex: '44', kind: 1, value: 68 },
  { key: 113, word: 'F12', dec: '69', hex: '45', kind: 1, value: 69 },
  { key: 114, word: 'PrintScreen', dec: '70', hex: '46', kind: 1, value: 70 },
  { key: 115, word: 'ScrollLock', dec: '71', hex: '47', kind: 1, value: 71 },
  { key: 116, word: 'Pause', dec: '72', hex: '48', kind: 1, value: 72 },
  { key: 117, word: 'Insert', dec: '73', hex: '49', kind: 1, value: 73 },
  { key: 118, word: 'Home', dec: '74', hex: '4A', kind: 1, value: 74 },
  { key: 119, word: 'PageUp', dec: '75', hex: '4B', kind: 1, value: 75 },
  { key: 120, word: 'DeleteForward', dec: '76', hex: '4C', kind: 1, value: 76 },
  { key: 121, word: 'End', dec: '77', hex: '4D', kind: 1, value: 77 },
  { key: 122, word: 'PageDown', dec: '78', hex: '4E', kind: 1, value: 78 },
  { key: 123, word: 'ArrowRight', dec: '79', hex: '4F', kind: 1, value: 79 },
  { key: 124, word: 'ArrowLeft', dec: '80', hex: '50', kind: 1, value: 80 },
  { key: 125, word: 'ArrowDown', dec: '81', hex: '51', kind: 1, value: 81 },
  { key: 126, word: 'ArrowUp', dec: '82', hex: '52', kind: 1, value: 82 },
  { key: 127, word: 'NumLock', dec: '83', hex: '53', kind: 1, value: 83 },
  { key: 128, word: 'Clear', dec: '83', hex: '53', kind: 1, value: 83 },
  { key: 160, word: 'F13', dec: '104', hex: '68', kind: 0, value: 104 },
  { key: 161, word: 'F14', dec: '105', hex: '69', kind: 0, value: 105 },
  { key: 162, word: 'F15', dec: '106', hex: '6A', kind: 0, value: 106 },
  { key: 163, word: 'F16', dec: '107', hex: '6B', kind: 0, value: 107 },
  { key: 164, word: 'LeftControl', dec: '224', hex: 'E0', kind: 0, value: 224 },
  { key: 165, word: 'LeftShift', dec: '225', hex: 'E1', kind: 0, value: 225 },
  { key: 166, word: 'LeftAlt', dec: '226', hex: 'E2', kind: 0, value: 226 },
  { key: 167, word: 'LeftGUI', dec: '227', hex: 'E3', kind: 0, value: 227 },
  {
    key: 168,
    word: 'RightControl',
    dec: '228',
    hex: 'E4',
    kind: 0,
    value: 228,
  },
  { key: 169, word: 'RightShift', dec: '229', hex: 'E5', kind: 0, value: 229 },
  { key: 170, word: 'RightAlt', dec: '230', hex: 'E6', kind: 0, value: 230 },
  { key: 171, word: 'RightGUI', dec: '231', hex: 'E7', kind: 0, value: 231 },
]

/********************************************************************************
 * @brief: 获取 HID 键码映射（主键名 + 别名）
 * @return {*}
 ********************************************************************************/
export const getHIDCodeMapStr = () => {
  return hidKeyCode.reduce((map, curKey) => {
    // 主键名映射
    map.set(curKey.word, curKey)

    // 别名映射（包含组合形式）
    if (curKey.aliases && curKey.aliases.length > 0) {
      curKey.aliases.forEach(alias => {
        map.set(alias, curKey)
      })
    }

    return map
  }, new Map<string, (typeof hidKeyCode)[0]>())
}

/********************************************************************************
 * @brief: 获取 HID 键码映射（value 映射）
 * @return {*}
 ********************************************************************************/
export const getHIDCodeMapStrNum = () => {
  return hidKeyCode.reduce(
    (pre, cur) => pre.set(cur.value, cur),
    new Map<number, (typeof hidKeyCode)[0]>()
  )
}
